### PR TITLE
added the pic of brock

### PR DESCRIPTION
**Pull request by Abhishekvermaa**
issue no.#4

### CODE REVIEW

**Comment by Abhishekvermaa** [comment]
pls add the picture of brock ,because I uploaded in the wrong folder but now i fixed that issue.

**Comment by iamartyaa** [comment]
I fixed that issue myself so I cannot merge this PR. Thank you

**Comment by Abhishekvermaa** [comment]
Okay

**Comment by Abhishekvermaa** [comment]
Okay

**Pull request closed without merging**
