### PR TITLE
Horizontal scroll bar issue resolved #282

### LINKED ISSUE #282: Horizontal scroll bar should be removed, for more good experience

### PR DESCRIPTION
**Pull request by ashwintelmore**
please add hacktoberfest-accepted tag

### CODE REVIEW

**Comment by ashwintelmore** [comment]
i have resolved the conflict can you please merged it?

**Comment by ashwintelmore** [comment]
@jackson-roberio can you please review my pr or suggest me some changes you want

**Comment by jackson-roberio** [comment]
> @jackson-roberio can you please review my pr or suggest me some changes you want

Hello, I'm not the owner or maintainer of the repository, sorry.

**Comment by Raunak173** [comment]
Hi, there is still a merge conflict. Please resolve it and then start a pr.

**Comment by ashwintelmore** [comment]
hey @Raunak173  i have resolved the conflict, do i need to create new pr

**Pull request closed without merging**
